### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TunHigh** [Labality/Boss#1]
- `2021-07-29 [19:05:39] [Server thread/INFO]: Enabling Boss v0.0.1
- 2021-07-29 [19:05:39] [Server thread/INFO]: Boss > Đang hình thành boss với mã: quybucu
- 2021-07-29 [19:05:39] [Server thread/INFO]: Boss > Load spawn của boss quybucu thành công! Spawn là: Position(level=boss,x=439,y=106,z=86)
- 2021-07-29 [19:05:39] [Server thread/INFO]: Boss > Model quybucu không tồn tại skin. Bỏ qua boss.
- 2021-07-29 [19:05:39] [Server thread/INFO]: Boss > Đang hình thành boss với mã: 
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type bool" (EXCEPTION) in "plugins/Boss-stable/src/Labality/Boss/Main" at line 62
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #0 plugins/Boss-stable/src/Labality/Boss/Main(62): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[51] Trying to access array offset on value of type bool, string[101] C:\Users\Administrator\Desktop\SkyBlock\Skyblock log 3\plugins\Boss-stable\src\L, integer 62, array[9])
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #1 plugins/Boss-stable/src/Labality/Boss/Main(46): Labality\Boss\Main->resourceFletch()
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginBase(116): Labality\Boss\Main->onEnable()
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Labality\Boss\Main)
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Labality\Boss\Main)
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[55] C:\Users\Administrator\Desktop\SkyBlock\Skyblock log 3\, string[63] C:\Users\Administrator\Desktop\SkyBlock\Skyblock log 3\plugins\)
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
- 2021-07-29 [19:05:39] [Server thread/CRITICAL]: #9 pmsrc(11): require(string[110] phar://C:/Users/Administrator/Desktop/SkyBlock/Skyblock log 3/PocketMine-MP.phar)
- 2021-07-29 [19:05:39] [Server thread/INFO]: Disabling Boss v0.0.1`

**Comment by Labality** [comment]
Hmm, can you show me your config files. Sorry for not making this user friendly.

**Comment by Labality** [comment]
Please make sure that your config files format is the same as the default.yml one

**Comment by Phuongaz** [comment]
Fixed (#3 )
